# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'yiju' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for yiju

  pod 'RSKImageCropper'
  pod 'QBImagePickerController'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  
  target 'yiju-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'yijuTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
